### ISSUE TITLE
Import Dataset

### ISSUE THREAD

**Issue by arfbrkdmr** [natdebru/OpenCV-Video-Label#5]
Hi,

Firstly, thank you for this amazing tool.
I face an error when I try to choose a folder for Importing dataset. 
I tried to run in Windows and Linux platforms but I faced error in boths.
By the way I tried for all dataset formats.

> Traceback (most recent call last):
  File "C:\path\to\Python\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\path\to\Python\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\path\to\OpenCV-Video-Label-master\top_menu.py", line 113, in import_dataset
    success, padded_preview = self.parent.pad_image(cropped)
AttributeError: 'MainWindow' object has no attribute 'pad_image'

> Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\path\to\Python\Python35\lib\threading.py", line 923, in _bootstrap_inner
    self.run()
  File "C:\path\to\Python\Python35\lib\threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "C:\path\to\OpenCV-Video-Label-master\top_menu.py", line 113, in import_dataset
    success, padded_preview = self.parent.pad_image(cropped)
AttributeError: 'MainWindow' object has no attribute 'pad_image

**Comment by natdebru** [comment]
Thank you, 
You are right, when I added support for the new exporting formats I changed the dataset structure, which now leads to some issues when importing an existing dataset. I will try to fix it when I have some time.
